#pragma once

// Hard-wired settings

#define ENVMAP_USE_IMPORTANCE_SAMPLING

//#define MATERIAL_GGX_SAMPLING_COS
//#define MATERIAL_GGX_SAMPLING_ALL_NORMALS
#define MATERIAL_GGX_SAMPLING_VISIBLE_NORMALS

//#define MIS_BALANCE_HEURISTIC
#define MIS_POWER_HEURISTIC
