#pragma once

// Hard-wired settings

//#define DIRECT_ILLUMINATION_SAMPLE_LIGHTS_ONLY_ALLLIGHTS
#define DIRECT_ILLUMINATION_SAMPLE_LIGHTS_SINGLESAMPLE
//#define DIRECT_ILLUMINATION_SAMPLE_BRDF_ONLY
//#define DIRECT_ILLUMINATION_USE_MIS

#define ENVMAP_USE_IMPORTANCE_SAMPLING

